name: Execute Parellel Testing
on: push
jobs:
 package1:
    runs-on: ubuntu-22.04
    steps:
      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
           ref: gh-pages
           path: gh-pages
      - name: Test marketplace action
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
             allure_results: build/allure-results
             gh_pages: gh-pages
             allure_report: allure-report
             allure_history: allure-history
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
               PUBLISH_BRANCH: gh-pages
               PUBLISH_DIR: allure-history
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
            runTests: false
            record: true
            browser: chrome
            headed: true
            build: npm run package1
 package3:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress Test Report
        uses: actions/upload-artifact@v4  
        with:
            name: Test Report
            path: cypress/reports/html # or path/to/artifact
      - name: Cypress run
        uses: cypress-io/github-action@v6
      
        with:
            runTests: false
            record: true
            browser: chrome
            headed: true
            build: npm run package4
